name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [created]

env:
  DOCKER_IMAGE_NAME: trilium_on_render
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_TAG: latest
  GITHUB_REPOSITORY: d3vmav/trilium_on_render

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_SECRET }}

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} . -f DD

    - name: Tag Docker image
      run: docker tag ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}

    - name: Push Docker image
      run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}

    # Render redeploy
    - name: Render Redeploy
      if: success()
      run: |
        curl --request POST \
          --url ${{ secrets.RENDER_DEPLOY_HOOK_URL }} \
          --header 'accept: application/json' \
          --header 'content-type: application/json' \
          --data '
        {
          "clearCache": "clear"
        }
        '

